server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization';
            add_header 'Access-Control-Max-Age' '86400';
            return 204;
        }
        proxy_hide_header access-control-allow-origin;
        proxy_pass http://api:3400/;
        proxy_set_header Host $host;
    }

    location /pool-stats/ {
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'Content-Type';
            return 204;
        }
        proxy_hide_header access-control-allow-origin;
        proxy_pass http://host.docker.internal:3337/;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
